// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// CrawlProxy is the golang structure for table crawl_proxy.
type CrawlProxy struct {
	Id           int         `json:"id"           ` // 主键ID
	TargetDomain string      `json:"targetDomain" ` // 目标网站顶级域名
	ProxyUrl     string      `json:"proxyUrl"     ` // 代理地址
	ProxyStatus  int         `json:"proxyStatus"  ` // 代理状态. 0-停用,1-使用中
	CreateUser   string      `json:"createUser"   ` // 创建者
	CreateTime   *gtime.Time `json:"createTime"   ` // 创建时间
	UpdateUser   string      `json:"updateUser"   ` // 修改者
	UpdateTime   *gtime.Time `json:"updateTime"   ` // 修改时间
}
