// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-to-crawl-common/internal/dao/internal"
)

// internalCrawlUploadQueueDao is internal type for wrapping internal DAO implements.
type internalCrawlUploadQueueDao = *internal.CrawlUploadQueueDao

// crawlUploadQueueDao is the data access object for table crawl_upload_queue.
// You can define custom methods on it to extend its functionality as you wish.
type crawlUploadQueueDao struct {
	internalCrawlUploadQueueDao
}

var (
	// CrawlUploadQueue is globally public accessible object for table crawl_upload_queue operations.
	CrawlUploadQueue = crawlUploadQueueDao{
		internal.NewCrawlUploadQueueDao(),
	}
)

// Fill with you ideas below.
