// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-to-crawl-common/internal/dao/internal"
)

// internalCrawlVodDao is internal type for wrapping internal DAO implements.
type internalCrawlVodDao = *internal.CrawlVodDao

// crawlVodDao is the data access object for table crawl_vod.
// You can define custom methods on it to extend its functionality as you wish.
type crawlVodDao struct {
	internalCrawlVodDao
}

var (
	// CrawlVod is globally public accessible object for table crawl_vod operations.
	CrawlVod = crawlVodDao{
		internal.NewCrawlVodDao(),
	}
)

// Fill with you ideas below.
