// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-to-crawl-common/internal/dao/internal"
)

// internalCrawlVodConfigDao is internal type for wrapping internal DAO implements.
type internalCrawlVodConfigDao = *internal.CrawlVodConfigDao

// crawlVodConfigDao is the data access object for table crawl_vod_config.
// You can define custom methods on it to extend its functionality as you wish.
type crawlVodConfigDao struct {
	internalCrawlVodConfigDao
}

var (
	// CrawlVodConfig is globally public accessible object for table crawl_vod_config operations.
	CrawlVodConfig = crawlVodConfigDao{
		internal.NewCrawlVodConfigDao(),
	}
)

// Fill with you ideas below.
