// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CrawlProxy is the golang structure of table crawl_proxy for DAO operations like Where/Data.
type CrawlProxy struct {
	g.Meta       `orm:"table:crawl_proxy, do:true"`
	Id           interface{} // 主键ID
	TargetDomain interface{} // 目标网站顶级域名
	ProxyUrl     interface{} // 代理地址
	ProxyStatus  interface{} // 代理状态. 0-停用,1-使用中
	CreateUser   interface{} // 创建者
	CreateTime   *gtime.Time // 创建时间
	UpdateUser   interface{} // 修改者
	UpdateTime   *gtime.Time // 修改时间
}
