// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// CrawlDictDao is the data access object for table crawl_dict.
type CrawlDictDao struct {
	table   string           // table is the underlying table name of the DAO.
	group   string           // group is the database configuration group name of current DAO.
	columns CrawlDictColumns // columns contains all the column names of Table for convenient usage.
}

// CrawlDictColumns defines and stores column names for table crawl_dict.
type CrawlDictColumns struct {
	Id         string // ID
	Namespace  string // 命名空间
	DictKey    string // 键名
	DictValue  string // 键值
	DictSort   string //
	DictStatus string // 状态. 0-停用；1-启用
	DictDesc   string // 描述
}

// crawlDictColumns holds the columns for table crawl_dict.
var crawlDictColumns = CrawlDictColumns{
	Id:         "id",
	Namespace:  "namespace",
	DictKey:    "dict_key",
	DictValue:  "dict_value",
	DictSort:   "dict_sort",
	DictStatus: "dict_status",
	DictDesc:   "dict_desc",
}

// NewCrawlDictDao creates and returns a new DAO object for table data access.
func NewCrawlDictDao() *CrawlDictDao {
	return &CrawlDictDao{
		group:   "default",
		table:   "crawl_dict",
		columns: crawlDictColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *CrawlDictDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *CrawlDictDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *CrawlDictDao) Columns() CrawlDictColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *CrawlDictDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *CrawlDictDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *CrawlDictDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
