// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-to-crawl-video/internal/dao/internal"
)

// internalCrawlDictDao is internal type for wrapping internal DAO implements.
type internalCrawlDictDao = *internal.CrawlDictDao

// crawlDictDao is the data access object for table crawl_dict.
// You can define custom methods on it to extend its functionality as you wish.
type crawlDictDao struct {
	internalCrawlDictDao
}

var (
	// CrawlDict is globally public accessible object for table crawl_dict operations.
	CrawlDict = crawlDictDao{
		internal.NewCrawlDictDao(),
	}
)

// Fill with you ideas below.
