// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-to-crawl-video/internal/dao/internal"
)

// internalCrawlProxyDao is internal type for wrapping internal DAO implements.
type internalCrawlProxyDao = *internal.CrawlProxyDao

// crawlProxyDao is the data access object for table crawl_proxy.
// You can define custom methods on it to extend its functionality as you wish.
type crawlProxyDao struct {
	internalCrawlProxyDao
}

var (
	// CrawlProxy is globally public accessible object for table crawl_proxy operations.
	CrawlProxy = crawlProxyDao{
		internal.NewCrawlProxyDao(),
	}
)

// Fill with you ideas below.
