// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CrawlVodConfigTask is the golang structure of table crawl_vod_config_task for DAO operations like Where/Data.
type CrawlVodConfigTask struct {
	g.Meta      `orm:"table:crawl_vod_config_task, do:true"`
	Id          interface{} // 主键ID
	VodConfigId interface{} // vod_config表ID
	TaskStatus  interface{} // 任务状态. 0-初始化; 1-进行中; 2-任务失败; 3-任务结束
	CreateUser  interface{} // 创建者
	CreateTime  *gtime.Time // 创建时间
	UpdateUser  interface{} // 修改者
	UpdateTime  *gtime.Time // 修改时间
}
