// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CrawlVodItem is the golang structure of table crawl_vod_item for DAO operations like Where/Data.
type CrawlVodItem struct {
	g.Meta      `orm:"table:crawl_vod_item, do:true"`
	Id          interface{} //
	TvId        interface{} // VOD表ID
	TvItemMd5   interface{} // 集数MD5
	CrawlStatus interface{} // 抓取状态.0-INIT;1-自动补全视频信息中;2-补充视频信息失败;3-补充视频信息成功;4-补充TV ID信息中;5-补充TV ID信息失败;6-补充TV ID信息成功
	SeedUrl     interface{} // 种子URL
	SeedParams  interface{} // 种子URL参数
	ErrorMsg    interface{} // 错误信息
	Episodes    interface{} // 集数
	CreateUser  interface{} // 创建者
	CreateTime  *gtime.Time // 创建时间
	UpdateUser  interface{} // 修改者
	UpdateTime  *gtime.Time // 修改时间
}
