server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level: "all"
  stdout: true

# mysql:账号:密码@tcp(地址:端⼝)/数据库名称
database:
  default:
    link: mysql:root:root@tcp(172.27.178.58:3306)/go_to_crawl
    debug: true
  logger:
    Path: D:\app\go-to-crawl\logs\sql
    Level: all
    Stdout: true

crawl:
  hostLabel: hostForM3U8
  browserProxyPath: D:\ApplicationsPro\browsermob-proxy\bin\browsermob-proxy.bat
  #  http://chromedriver.storage.googleapis.com/index.html 驱动下载地址 需要对应浏览器版本TestNunuyyWithParams
  chromeDriverPath: D:\ApplicationsPro\chromedriver.exe
  chromeExePath: C:\Users\Administrator\AppData\Local\MyChrome\Chrome\Application\chrone.exe

  chromeHeadless: false # 无头模式（linux等无界面渲染模式需设置为true）
  userDataDir: D:\ApplicationsPro\chromeData # 谷歌缓存的用户信息，用于让selenium记录用户登录状态
  debug:
    disableDB: false # 不配置默认false，表示要做某些数据库操作。本地调试某些场景需要关闭一下数据库操作
    notDownloadAll: true # 不配置默认false，表示下载所有TS片段。本地调试某些场景只需要下载部分TS加快调试速度
  maxTrans: 5 #本机最大同时转码数量
  openVodTaskList: [ "downloadMp4Type3Task" ]



