// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// CrawlVodConfigTask is the golang structure for table crawl_vod_config_task.
type CrawlVodConfigTask struct {
	Id          int         `json:"id"          ` // 主键ID
	VodConfigId int         `json:"vodConfigId" ` // vod_config表ID
	TaskStatus  int         `json:"taskStatus"  ` // 任务状态. 0-初始化; 1-进行中; 2-任务失败; 3-任务结束
	CreateUser  string      `json:"createUser"  ` // 创建者
	CreateTime  *gtime.Time `json:"createTime"  ` // 创建时间
	UpdateUser  string      `json:"updateUser"  ` // 修改者
	UpdateTime  *gtime.Time `json:"updateTime"  ` // 修改时间
}
