// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-to-crawl-vod/internal/dao/internal"
)

// internalCrawlQueueDao is internal type for wrapping internal DAO implements.
type internalCrawlQueueDao = *internal.CrawlQueueDao

// crawlQueueDao is the data access object for table crawl_queue.
// You can define custom methods on it to extend its functionality as you wish.
type crawlQueueDao struct {
	internalCrawlQueueDao
}

var (
	// CrawlQueue is globally public accessible object for table crawl_queue operations.
	CrawlQueue = crawlQueueDao{
		internal.NewCrawlQueueDao(),
	}
)

// Fill with you ideas below.
