// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-to-crawl-vod/internal/dao/internal"
)

// internalCrawlVodConfigTaskDao is internal type for wrapping internal DAO implements.
type internalCrawlVodConfigTaskDao = *internal.CrawlVodConfigTaskDao

// crawlVodConfigTaskDao is the data access object for table crawl_vod_config_task.
// You can define custom methods on it to extend its functionality as you wish.
type crawlVodConfigTaskDao struct {
	internalCrawlVodConfigTaskDao
}

var (
	// CrawlVodConfigTask is globally public accessible object for table crawl_vod_config_task operations.
	CrawlVodConfigTask = crawlVodConfigTaskDao{
		internal.NewCrawlVodConfigTaskDao(),
	}
)

// Fill with you ideas below.
